language: c

branches:
  except:
    - /^feature.*$/

sudo: false

env:
  matrix:
    - BUILD=gcc
    - BUILD=clang

script:
  - mkdir build
  - cd build
  - cmake ../src/
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - clang
    - cmake
    - doxygen
    - valgrind

