language: c

branches:
  except:
    - /^feature.*$/

sudo: false

env:
  matrix:
    - BUILD=gcc
    - BUILD=clang

script:
  - mkdir build
  - cd build
  - cmake ../src/
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-4.0
    - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
    - gcc-6
    - clang
    - cmake
    - doxygen
    - valgrind

