language: c

branches:
  except:
    - /^feature.*$/

sudo: false

env:
  matrix:
    - BUILD=gcc
    - BUILD=clang

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then
      case ${BUILD} in
        gcc)
          cmaake ./src/ &&
          make &&
          ;;
        clang)
          cmake -DCMAKE_TOOLCHAIN_FILE=cmake/clang.cmake ./src/ &&
          make &&
          ;;
      esac ;
    fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - clang
    - cmake
    - doxygen
    - valgrind

